export default [{
  id: 1,
  title: 'What is Lorem Ipsum?',
  description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
  image: 'https://image.ceneostatic.pl/data/custom_images/2713/custom_image.png',
  alt: 'Simply dummy text.',
  quantity: 20,
}, {
  id: 2,
  title: 'What is Lorem Ipsum?',
  description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
  image: 'https://image.ceneostatic.pl/data/custom_images/2713/custom_image.png',
  alt: 'Simply dummy text.',
  quantity: 20,
}, {
  id: 3,
  title: 'What is Lorem Ipsum?',
  description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
  image: 'https://image.ceneostatic.pl/data/custom_images/2713/custom_image.png',
  alt: 'Simply dummy text.',
  quantity: 20,
}, {
  id: 4,
  title: 'What is Lorem Ipsum?',
  description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
  image: 'https://image.ceneostatic.pl/data/custom_images/2713/custom_image.png',
  alt: 'Simply dummy text.',
  quantity: 20,
}, {
  id: 5,
  title: 'What is Lorem Ipsum?',
  description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
  image: 'https://image.ceneostatic.pl/data/custom_images/2713/custom_image.png',
  alt: 'Simply dummy text.',
  quantity: 20,
}];
